### ISSUE TITLE
project cant run under 0.3.0-alpha.0

### ISSUE THREAD

**Issue by v423** [teocloud/teo-nodejs#4]
enviroment:
- pnpm 8.15.8
- nodejs 22.0.0
- teo-nodejs 0.3.0-alpha.0

error: 
```
v423@v423deAir hello-teo % pnpm teo serve
/Users/v423/development/teo/hello-teo/node_modules/.pnpm/@teocloud+teo@0.3.0-alpha.0/node_modules/@teocloud/teo/index.js:331
ReadOnlyHeaderMap.prototype[customInspectSymbol] = function(_, inspectOptions) {
^

ReferenceError: ReadOnlyHeaderMap is not defined
    at Object.<anonymous> (/Users/v423/development/teo/hello-teo/node_modules/.pnpm/@teocloud+teo@0.3.0-alpha.0/node_modules/@teocloud/teo/index.js:331:1)
    at Module._compile (node:internal/modules/cjs/loader:1455:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
    at Module.load (node:internal/modules/cjs/loader:1265:32)
    at Module._load (node:internal/modules/cjs/loader:1081:12)
    at Module.require (node:internal/modules/cjs/loader:1290:19)
    at require (node:internal/modules/helpers:188:18)
    at Object.<anonymous> (/Users/v423/development/teo/hello-teo/node_modules/.pnpm/@teocloud+teo@0.3.0-alpha.0/node_modules/@teocloud/teo/teo.js:3:17)
    at Module._compile (node:internal/modules/cjs/loader:1455:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1534:10)
```

schema:
```
connector {
  provider: .sqlite,
  url: "sqlite:medicine.sqlite"
}

server {
  bind:("0.0.0.0", 8088)
}

model TestModel{
  @id @autoIncrement @readonly
  id: Int
  name: String
}

```

**Comment by victorteokw** [comment]
Hi @v423, alpha version may contain bugs and not recommended for production use. Noted and I will fix this in alpha.1.
